export const AUTH_SERVICE = {
    REQ_LOGIN_APPS: "REQ_LOGIN_APPS",
    SUCCES_LOGIN_APPS: "SUCCES_LOGIN_APPS",
    FAILED_LOGIN_APPS: "FAILED_LOGIN_APPS",
    SESSION_SUCCES: "SESSION_SUCCES",
    SESSION_FAILED: "SESSION_FAILED",
    REQ_SESSION: "REQ_SESSION",

    LOGOUT_USER:"LOGOUT USER",
    ADD_CART: "CART",
    ADD_TABLE_TOCART: "CART_TABLE_ADD",
}